name: build-it-please

on:
  create:
    tags:
      - v*

jobs:
  release-amd64:
    name: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: wangyoucao577/go-release-action@v1.18
      with:
        github_token: ${{ secrets.TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: 1.15
        binary_name: "umidns"